<?php

	/***************************************************************
	 * cssStyleOn - http://cssStyleOn.c0n.de 2008 by Stefan Baur
	 *--------------------------------------------------------------
	 *  src/layout.php
	 *     generic funtions to create some nice tabbed layout
	 *--------------------------------------------------------------
	 *  TODO: focus the right input when switching tabs
	 **************************************************************/

$layout_tabs=array(	); // store all tabs we have

	// add a new tab to our layout
function layoutAddTab($tab_group,$id,$title,$layoutTabFunc)
	{
	global $layout_tabs;

	$layout_tabs[$tab_group][]=array('id'=>$id,'title'=>$title,'layoutTabFunc'=>$layoutTabFunc);
	}


//--------------------------------------------------------------------------------

	// create the needed JavaScript for handling our tabs
function layoutOutScripts()
	{
	global $layout_tabs;
?>
//////////////////////////////////////////////////////////////////////////////
// general layout scripts - generated by layout.php
//////////////////////////////////////////////////////////////////////////////

var currentButtonIDs={};

function layoutButtonClick(group,id)
	{
	currentButtonIDs[group] = id;

		// reset all buttons
	switch(group)
		{
<?php foreach($layout_tabs as $tab_group => $tabs) { ?>
		case '<?php echo $tab_group?>':
<?php foreach($tabs as $tab) { ?>
			document.getElementById("<?php echo $tab_group?>_<?php echo $tab['id']?>Button").className = "buttonNormal";
<?php } ?>
			break;
<?php } ?>
		}

		// mark current button as active
	document.getElementById(group+'_'+id+'Button').className = "buttonPressed";

	layoutShowRightTab(group,id);
	}


function layoutButtonOver(group,id)
	{
	var button = document.getElementById(group+'_'+id+'Button');
	
	if (id == currentButtonIDs[group])
		{
		button.className = "buttonPressedHover";
		}
	else
		{
		button.className = "buttonHover";
		}
	}


function layoutButtonOut(group,id)
	{
	var button = document.getElementById(group+'_'+id+'Button');
	
	if (id == currentButtonIDs[group])
		{
		button.className = "buttonPressed";
		}
	else
		{
		button.className = "buttonNormal";
		}
	}

function layoutShowRightTab(group,id)
	{
	switch(group)
		{
<?php foreach($layout_tabs as $tab_group => $tabs) { ?>
		case '<?php echo $tab_group?>':
<?php foreach($tabs as $tab) { ?>
			document.getElementById("<?php echo $tab_group?>_<?php echo $tab['id']?>Tab").style.display = "none";
<?php } ?>
			break;
<?php } ?>
		}
	document.getElementById(group+'_'+id+"Tab").style.display = "";
	}

<?
	}

	// generate our tab buttons
function layoutOutButtons($group)
	{
	global $layout_tabs;
?>
                        <ul class="buttons">
<?
	foreach($layout_tabs[$group] as $tab)
		{
?>
                            <li class="buttonNormal" onclick="layoutButtonClick('<?php echo $group?>','<?php echo $tab['id']?>');" onmouseover="layoutButtonOver('<?php echo $group?>','<?php echo $tab['id']?>')" onmouseout="layoutButtonOut('<?php echo $group?>','<?php echo $tab['id']?>')" id="<?php echo $group?>_<?php echo $tab['id']?>Button">
                               &nbsp;<?php echo $tab['title']?>&nbsp;
                            </li>

<?
		}
?>
                        </ul>
<?

	}

	// generate our tab contents
function layoutOutTabs($group)
	{
	global $layout_tabs;
	foreach($layout_tabs[$group] as $tab)
		{
?>
                     <div class="tabContent" style="display: none;" id="<?php echo $group?>_<?php echo $tab['id']?>Tab">
<?php $tab['layoutTabFunc'](); ?>
                     </div>
<?
		}
	}


?>